### ISSUE TITLE
Card addressed? 

### ISSUE THREAD

**Issue by hippi345** [hippi345/randobotjava#22]
Was this card addressed in one of your recent PR's?

https://github.com/hippi345/randobotjava/projects/1#card-31832758

**Comment by RiskRunner0** [comment]
Not yet, I think what we need to do is have some kind of structure on the Game class that exposes all of the drawable items.  Right now it's just explicitly the item and the treasure, but if we want to add multiple treasures and you have to pick them all up, we'd want just some kind of enumerable object that we would draw each time.

**Comment by hippi345** [comment]
makes sense. that way it could 1 treasure or 69 treasures and we are good. Closing the issue as it was inquiring on the card and the card will not be placed in the done bucket yet.
