### ISSUE TITLE
Is card addressed?

### ISSUE THREAD

**Issue by hippi345** [hippi345/randobotjava#26]
https://github.com/hippi345/randobotjava/projects/1#card-31542444

Is this card addressed by the creation of IGame? Or is there more to do in terms of using this interface to mark this card as resolved?

https://github.com/hippi345/randobotjava/blob/981760cbcf9c1b49c6886ce94d659f5a67ea8dc6/src/sample/interfaces/IGame.java#L8

**Comment by RiskRunner0** [comment]
Yeah this one's done.
