### ISSUE TITLE
Bot is being moved twice in one random movement

### ISSUE THREAD

**Issue by RiskRunner0** [hippi345/randobotjava#9]
Here:
https://github.com/hippi345/randobotjava/blob/0eaffc817af7ae9ac06a194d306ab859be96eb75/src/sample/models/Bot.java#L39-L44

and here:
https://github.com/hippi345/randobotjava/blob/0eaffc817af7ae9ac06a194d306ab859be96eb75/src/sample/models/Bot.java#L129-L133

Following the flow of ```MoveRandomly```, ```getPreferredMoves``` is called, and in that function, an actual move is executed.  Then another move is executed in the top level function

**Comment by hippi345** [comment]
JoelDev implements a fix for this but the PR to master would be massive for some reason so should I compare against another branch for the PR? 
Try to make a PR for joelDev to Master and see amount of changes and you will know what I am saying.
@QueenCitySmitty

**Comment by RiskRunner0** [comment]
What I would do is make sure your master is latest, then branch off for a fix and do the fix there.  Just use that branch for the fix only

**Comment by hippi345** [comment]
Resolved with Pull Request and merged. Duplicate movements in determining preferred move was removed.
